mysql:
  image: mariadb:10.3
  environment:
    - "MYSQL_USER=rpp"
    - "MYSQL_PASSWORD=NotASecurePassword!"
    - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    - "MYSQL_DATABASE=rpp_${RAILS_ENV}"
  ports:
    - "3306:3306"
  volumes:
    - rpp-mysql:/var/lib/mysql
rails-pipeline-practice:
  build: .
  links:
    - mysql
  ports:
    - "3000:3000"
  environment:
    - "RAILS_ENV=${RAILS_ENV}"
    - DB_NAME=rpp
    - DB_HOST=mysql
    - DB_USER=rpp
    - DB_PASSWORD="NotASecurePassword!"
nginx:
  image: nginx:1.13
  ports:
    - "8080:80"
  links:
    - "rails-pipeline-practice:app"
  volumes:
    - ./deployment/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
  environment:
    - APP_CONTAINER=app
  command: /bin/bash -c "envsubst '$$APP_CONTAINER' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
