---

default: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>

development:
  <<: *default

local_integration:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
